name: Tests

on:
  push:

jobs:
  Config-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          git clone https://github.com/Gufran/traefik
          cd traefik
          git checkout consul-connect-backend
          make build-image
      - name: Run tests
        run: make
